// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var UniversalRouter = require("universal-router");

var Router = /* module */[];

function make(routes, options, param) {
  return new UniversalRouter.Router(routes, options);
}

exports.Router = Router;
exports.make = make;
/* universal-router Not a pure module */
